/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControlCuentas;
import controlador.ControlPrestamos;
import javax.swing.table.DefaultTableModel;
import modelo.Banco;
import modelo.Cuenta;
import modelo.Usuario;

/**
 *
 * @author Usuario
 */
public class FrmTablaAModificar extends javax.swing.JFrame {
    //Crea nueva cuenta para ser usada por todo el frame 
    Cuenta cuenta = new Cuenta();

    /**
     * Creates new form FrmTablaAModificar
     */
    public FrmTablaAModificar() {
        initComponents();
        actualizaTabla();
        ocultaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCuentas = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione cuenta a modificar"));

        tablaCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCuentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCuentas);

        btnModificar.setText("Modificar cuenta");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(255, 0, 0));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnVolver))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //btn volver: Cierra la ventana y devuelve al frm anterior 
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        FrmCuentas frmCuentas = new FrmCuentas();
        this.dispose();
        frmCuentas.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed
    
    //Btn Modificar: Crea un nuevo frmModificarCuenta y le asigna los valores de la fila seleccionada
    //a los labels y txtFields
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        FrmModificarCuenta frmModificarCuenta = new FrmModificarCuenta();
        frmModificarCuenta.lblIdCuenta.setText(String.valueOf(cuenta.getIdcuenta()));
        frmModificarCuenta.txtFieldSaldo.setText(String.valueOf(cuenta.getSaldo()));
        frmModificarCuenta.txtFieldNro.setText(cuenta.getNrodecuenta());
        frmModificarCuenta.txtFieldIdBanco.setText(String.valueOf(cuenta.getIdbanco().getIdbanco()));
        frmModificarCuenta.txtFieldIdUsuario.setText(String.valueOf(cuenta.getIdusuario().getIdusuario()));
        frmModificarCuenta.setVisible(true);
    }//GEN-LAST:event_btnModificarActionPerformed
    
    //Click en tabla: Toma los valores de fila seleccionada y se los asigna a la cuenta creada inicialmente
    private void tablaCuentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCuentasMouseClicked
        // TODO add your handling code here:
        String idCuenta = String.valueOf(tablaCuentas.getValueAt(tablaCuentas.getSelectedRow(),0));
        String nroCuenta = String.valueOf(tablaCuentas.getValueAt(tablaCuentas.getSelectedRow(),1));
        String banco = String.valueOf(tablaCuentas.getValueAt(tablaCuentas.getSelectedRow(),9));
        String saldo = String.valueOf(tablaCuentas.getValueAt(tablaCuentas.getSelectedRow(),2));
        String idUsuario = String.valueOf(tablaCuentas.getValueAt(tablaCuentas.getSelectedRow(),10));
        
        cuenta.setIdcuenta(Integer.valueOf(idCuenta));
        cuenta.setNrodecuenta(nroCuenta);
        
        Banco banco2 = new Banco();
        banco2.setIdbanco(Integer.valueOf(banco));
        cuenta.setIdbanco(banco2);
        
        cuenta.setSaldo(Double.valueOf(saldo));
        
        Usuario usuario2 = new Usuario();
        usuario2.setIdusuario(Integer.valueOf(idUsuario));
        cuenta.setIdusuario(usuario2);
    }//GEN-LAST:event_tablaCuentasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablaAModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablaAModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablaAModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablaAModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablaAModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCuentas;
    // End of variables declaration//GEN-END:variables
    
    
    //Llena la tabla con los valores obtenidos de la bbdd
    private void actualizaTabla(){
        DefaultTableModel listaCuentas;
        listaCuentas = ControlCuentas.listarTodasLasCuentas();
        
        tablaCuentas.setModel(listaCuentas);
    
    }
    
    //Oculta columnas de la tabla 
    private void ocultaCampos() {
        tablaCuentas.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaCuentas.getColumnModel().getColumn(0).setMinWidth(0);
        tablaCuentas.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        tablaCuentas.getColumnModel().getColumn(3).setMaxWidth(0);
        tablaCuentas.getColumnModel().getColumn(3).setMinWidth(0);
        tablaCuentas.getColumnModel().getColumn(3).setPreferredWidth(0);
        
        tablaCuentas.getColumnModel().getColumn(4).setMaxWidth(0);
        tablaCuentas.getColumnModel().getColumn(4).setMinWidth(0);
        tablaCuentas.getColumnModel().getColumn(4).setPreferredWidth(0);
        
        tablaCuentas.getColumnModel().getColumn(5).setMaxWidth(0);
        tablaCuentas.getColumnModel().getColumn(5).setMinWidth(0);
        tablaCuentas.getColumnModel().getColumn(5).setPreferredWidth(0);
        
        tablaCuentas.getColumnModel().getColumn(6).setMaxWidth(0);
        tablaCuentas.getColumnModel().getColumn(6).setMinWidth(0);
        tablaCuentas.getColumnModel().getColumn(6).setPreferredWidth(0);
        
        tablaCuentas.getColumnModel().getColumn(7).setMaxWidth(0);
        tablaCuentas.getColumnModel().getColumn(7).setMinWidth(0);
        tablaCuentas.getColumnModel().getColumn(7).setPreferredWidth(0);
        
        tablaCuentas.getColumnModel().getColumn(8).setMaxWidth(0);
        tablaCuentas.getColumnModel().getColumn(8).setMinWidth(0);
        tablaCuentas.getColumnModel().getColumn(8).setPreferredWidth(0);
        
        
    }
}
